app = "FLY_APP_NAME"
primary_region = "iad"

[build]
  # Use the repository Dockerfile for the backend service
  # Point to the Dockerfile path so Fly's remote builder builds from source.
  dockerfile = "backend/Dockerfile"

[env]
  PORT = "3000"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
  [[services.ports]]
    handlers = ["http"]
    port = 80
