name: CI & Deploy to Fly

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install backend deps
        working-directory: ./backend
        run: npm ci
      - name: Run tests
        working-directory: ./backend
        run: npm test -- --detectOpenHandles --runInBand --verbose

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Install Flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "${HOME}/.fly/bin" >> $GITHUB_PATH
      - name: Deploy to Fly (remote build)
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}
        run: |
          # Use Fly's remote builder to avoid pushing to the registry directly from CI.
          # Note: `--region` is not a valid flag for flyctl deploy; use fly.toml primary_region or --primary-region to override.
          ${HOME}/.fly/bin/flyctl deploy --config fly.toml --app ${{ secrets.FLY_APP_NAME }} --remote-only
